version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dev_db
      - DB_USER=dev_user
      - DB_PASSWORD=dev_password
    depends_on:
      - db
  
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
  
  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - dev-redis-data:/var/lib/redis/data
    depends_on:
      - db

volumes:
  dev-db-data:
  dev-static-data:
  dev-redis-data: