# Generated by Django 4.0.8 on 2022-11-15 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryimagelink",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
